name: EC2_deployment

on:
  push:
    # branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Set environment variables
    - name: Set environment variables
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV }}" > .env

    # Step 4: Create and activate the virtual environment
    - name: Create and activate virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate  # Activate the virtual environment

    # Step 5: Install dependencies
    - name: Install dependencies
      run: |
        source venv/bin/activate  # Ensure the virtual environment is activated
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 6: Install Gunicorn
    - name: Install Gunicorn
      run: |
        source venv/bin/activate
        pip install gunicorn

    # Step 7: Deploy Flask application with Gunicorn
    - name: Deploy Flask application with Gunicorn
      run: |
        source venv/bin/activate
        # Stop any existing Flask application
        pkill -f "gunicorn" || true

        # Export environment variables
        export $(cat .env | xargs)
        
        # Start the Flask application using Gunicorn in the background
        nohup gunicorn --bind 0.0.0.0:8000 app:app > flask.log 2>&1 &

    # Step 8: Verify deployment
    - name: Verify deployment
      run: |
        curl -f http://localhost:8000/ || echo "Deployment verification failed"
